authors:
  geekatron:
    name: Geekatron
    description: Creator of the Tom Framework
    avatar: https://github.com/geekatron.png
  e128:
    name: e128
    description: Contributor
    avatar: https://github.com/e128.png
